### ISSUE TITLE
Php 5.6 backport

### ISSUE THREAD

**Issue by stolkchris** [rinvex/language#2]
Hi @Omranic,

This package is incredibly useful, and could potentially be something that can make a lot of people happy. I've created a backport to php 5.6 because some of us are still stuck on php 5.6 for some time due to "constraints".

In any case, it might be worthwhile mentioning this backport on your page to save potential users from having to do the port themselves :)

Thanks for the great package!

https://github.com/wubbajack/language

**Comment by Omranic** [comment]
Thanks @wubbajack for your contribution to the community.

While we're not interested in supporting old outdated software versions, we've seen the need for PHP 5.6 support for many of our packages, that's why we're currently re-considering this for a strategic update across the board. I'll keep this issue open until a decision is been taken and will update this issue then :)

**Comment by stolkchris** [comment]
Glad to hear! I understand it's not an easy decision to make. The fork will stay open for as long as is necessary.

Thanks again for the great packages!

**Comment by Omranic** [comment]
Thank you @wubbajack, honestly since PHP 5.6 already out of date and no longer actively maintained, we're not going to support it. But you still can fork the package, and add the following lines to your `composer.json` to use your copy of the package, you still have to sync any updates manually:
```php
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/username/repo"
        }
    ],
```

Hope you can upgrade to PHP7 soon to get benefit of all the awesome stuff 😉
